import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navigation from '@/components/sections/Navigation';
import { VisibilityProvider } from '@/contexts/visibility';
import CountriesAndLeagues from '@/components/sections/CountriesAndLeagues';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'MidField',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <VisibilityProvider>
        <body className={`${inter.className} box-border min-h-svh`}>
          <div className="grid h-full min-h-svh max-w-full grid-rows-[max-content,auto,max-content]">
            <header>
              <Navigation />
            </header>
            <main className="mx-auto h-full min-h-full w-full max-w-screen-xl">{children}</main>
            <footer className="text-black">Copyrights</footer>
          </div>
          <CountriesAndLeagues />
        </body>
      </VisibilityProvider>
    </html>
  );
}
